apiVersion: apps/v1
kind: Deployment

metadata:
    name: argo-server
    namespace: argo

spec:
    template:
        spec:
            containers:
                - name: arg-server
                  image: quay.io/argoproj/argocli:v3.4.4
                  args:
                    - server
                    - --auth-mode=server