apiVersion: argoproj.io/v1alpha1
kind: Sensor

metadata:
    name: webhook-eventsource-sensor
    namespace: argo-events

spec:

    template:
        serviceAccountName: operate-workflow-sa

    dependencies:
        - name: demo-server-code-change-event
          eventSourceName: microservices-code-change-github-webhook-eventsource
          eventName: demo-server-code-change

    triggers:
        - template:
            name: demo-server-container-image-deployment-workflow-trigger
            argoWorkflow:
                operation: submit
                source:
                    resource:

                        #* defining the argo workflow
                        apiVersion: argoproj.io/v1alpha1
                        kind: Workflow

                        metadata:
                            generateName: demo-server-container-image-deployment-workflow-
                            namespace: argo

                        spec:
                            workflowTemplateRef:
                                name: demo-server-container-image-deployment-workflow-template