apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
    name: rabbitmq-kustomization
    namespace: default

resources:
    #* install the rabbitMQ cluster operator
    - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml

    - ./rabbitmq.cluster.yaml