apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster

metadata:
    name: rabbitmq-cluster
    namespace: rabbitmq-system

spec:
    replicas: 3

    rabbitmq:
        additionalConfig: |
            default_user=user
            default_pass=password

            log.console.level=debug