apiVersion: argoproj.io/v1alpha1
kind: EventSource

metadata:
    name: code-change-github-webhook-eventsource
    namespace: argo-events

spec:

    github:
        demo-server-code-change:
            repositories:
                - owner: Archisman-Mridha
                  names:
                    - cloudnative-tools
            webhook:
                endpoint: /demo-server-code-change
                port: "12000"
                method: POST
                url: http://demo-server-code-change.github-webhook.argo-eventsource.traefik.127.0.0.1.nip.io
            events:
                - push
            insecure: true
            active: true
            contentType: json