apiVersion: k3d.io/v1alpha3
kind: Simple

name: cloudnative-tools-testing

servers: 1
agents: 2

ports:
    - port: 80:80
      nodeFilters:
        - loadbalancer
    - port: 443:443
      nodeFilters:
        - loadbalancer

options:
    k3s:
        extraArgs:
            - arg: --no-deploy=traefik
              nodeFilters:
                - server:*