apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate

metadata:
    name: demo-server-container-image-deployment-workflow-template
    namespace: argo

spec:
    entrypoint: main

    volumeClaimTemplates:
        - metadata:
            name: workspace
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
                requests:
                    storage: 65Mi

    templates:
        - name: main
          steps:
            - - name: git-clone
                template: git-clone
            - - name: build-and-push
                template: build-and-push

        - name: git-clone
          container:
            image: alpine/git:latest
            workingDir: /workspace
            volumeMounts:
                - mountPath: /workspace
                  name: workspace
            command:
                - git
            args:
                - clone
                - https://github.com/Archisman-Mridha/cloudnative-tools
                - .

        - name: build-and-push
          volumes:
            - name: dockerhub-credentials-secret
              secret:
                secretName: dockerhub-credentials-secret
          container:
            image: moby/buildkit:v0.9.3-rootless
            volumeMounts:
                - mountPath: /workspace
                  name: workspace
                - mountPath: /.docker
                  name: dockerhub-credentials-secret
            workingDir: /workspace/argo-ecosystem/demo-server
            env:
                - name: BUILDKITD_FLAGS
                  value: --oci-worker-no-process-sandbox
                - name: DOCKER_CONFIG
                  value: /.docker
            command:
                - buildctl-daemonless.sh
            args:
                - build
                - --frontend
                - dockerfile.v0
                - --local
                - context=.
                - --local
                - dockerfile=.
                - --output
                - type=image,name=docker.io/archismanmridha/demo-server:latest,push=true