apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: traefik-helm-installation
    namespace: argocd

spec:
    project: default

    destination:
        server: https://kubernetes.default.svc
        namespace: hub-agent

    source:
        repoURL: https://helm.traefik.io/traefik
        chart: traefik
        targetRevision: 20.8.0
        helm:
            releaseName: traefik
            values: |
                additionalArguments:
                    - --experimental.hub
                    - --hub

                providers:
                    kubernetesIngress:
                        allowExternalNameServices: true

                metrics:
                    prometheus:
                        addRoutersLabels: true

                ports:
                    metrics:
                        expose: true
                    traefikhub-tunl:
                        protocol: TCP
                        port: 9901
                        expose: true
                        exposedPort: 9901

                service:
                    type: ClusterIP

    syncPolicy:
        automated:
            prune: true
            selfHeal: true