#* the namespace where helm installation will take place

apiVersion: v1
kind: Namespace

metadata:
    name: hub-agent

---

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: traefik-hub-agent-helm-installation
    namespace: argocd

spec:
    project: default

    destination:
        server: https://kubernetes.default.svc
        namespace: hub-agent

    source:
        repoURL: https://helm.traefik.io/traefik
        chart: hub-agent
        targetRevision: 1.2.1
        helm:
            releaseName: hub-agent
            values: |
                token: d0603012-2518-4b7f-8b4d-138385131c58

    syncPolicy:
        automated:
            prune: true
            selfHeal: true