#* the namespace where helm installation will take place

apiVersion: v1
kind: Namespace

metadata:
    name: hub-agent

---

apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: traefik-hub-agent-helm-installation
    namespace: argocd

spec:
    project: default

    destination:
        server: https://kubernetes.default.svc
        namespace: hub-agent

    source:
        repoURL: https://helm.traefik.io/traefik
        chart: hub-agent
        targetRevision: 1.2.1
        helm:
            releaseName: hub-agent
            values: |
                token: 4d09d574-229e-4982-83c1-517d1e18652d

    syncPolicy:
        automated:
            prune: true
            selfHeal: true