apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: traefik-helm-installation
    namespace: argocd

spec:
    project: default

    destination:
        server: https://kubernetes.default.svc
        namespace: hub-agent

    source:
        repoURL: https://helm.traefik.io/traefik
        chart: traefik
        targetRevision: 20.8.0
        helm:
            releaseName: traefik
            values: |
                experimental:
                    kubernetesGateway:
                        enabled: true

                #* using traefik hub to expose Kubernetes services to public internet
                hub:
                    enabled: true

    syncPolicy:
        automated:
            prune: true
            selfHeal: true