apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: networking

spec:
  ## Kernel probes to be traced.
  kprobes:

    - call: tcp_connect
      syscall: false ## Indicates that it’s not a syscall, but a regular kernel function.
      args:
        - index: 0
          type: sock ## 'sock' stands for socket.

    - call: tcp_close
      syscall: false
      args:
        - index: 0
          type: sock