apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: sys-setns

spec:
  kprobes:
    - call: __x64_sys_setns
      syscall: true
      args:
        - index: 0
          type: int
        - index: 1
          type: int