apiVersion: apps/v1
kind: Deployment

metadata:
    name: whoami-deployment
    namespace: default
    labels:
        app: whoami

spec:
    replicas: 1
    selector:
        matchLabels:
            app: whoami
    template:
        metadata:
            labels:
                app: whoami
        spec:
            containers:
                - image: docker.io/traefik/whoami:v1.6.1
                  name: whoami
                  ports:
                    - containerPort: 80
                      name: http
                  resources:
                    limits:
                        memory: 256Mi
                        cpu: 200m
