apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
    name: istio-kustomization
    namespace: istio-system

resources:
    - https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.1/standard-install.yaml

    - https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/jaeger.yaml

    - https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/prometheus.yaml
    - https://raw.githubusercontent.com/istio/istio/release-1.16/samples/addons/grafana.yaml

    - ./peerauthentication.yaml