apiVersion: apps/v1
kind: Deployment

metadata:
    name: sender-microservice-deployment
    namespace: microservices
    labels:
        app: sender

spec:
    replicas: 1

    selector:
        matchLabels:
            app: sender

    template:
        metadata:
            name: sender-microservice
            labels:
                app: sender
        spec:
            containers:
                - name: sender-microservice
                  image: archismanmridha/rabbitmq-sender-microservice:1.0.0
                  imagePullPolicy: Always
                  resources:
                    limits:
                        cpu: 200m
                        memory: 256Mi
                  ports:
                    - containerPort: 4000
                      protocol: TCP
                  env:
                    - name: RABBITMQ_CLUSTER_ADDRESS
                      value: amqp://user:password@rabbitmq-cluster.rabbitmq-system.svc.cluster.local:5672/
