apiVersion: v1
kind: Service

metadata:
    name: sender-microservice-service
    namespace: microservices
    labels:
        app: sender

spec:
    type: ClusterIP

    selector:
        app: sender

    ports:
        - name: grpc
          port: 4000
          targetPort: 4000
          protocol: TCP
          appProtocol: grpc