apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudnative-pg-demo-client
  namespace: default

spec:
  selector:
    matchLabels:
      app: cloudnative-pg-demo-client

  template:
    metadata:
      labels:
        app: cloudnative-pg-demo-client
    spec:
      containers:
        - name: cloudnative-pg-demo-client
          image: archismanmridha/cloudnative-pg-demo-client:latest
          imagePullPolicy: Always
          env:
            - name: POSTGRES_CLUSTER_URL
              value: postgres://users:6wB9Y3heSoJzgFYsLTHWjbanc4T9X7wcALX3MR5a3uLjV4JRPCElylfRhbjgbxKI@main-rw.default.svc.cluster.local:5432/users?sslmode=disable
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
