apiVersion: apps/v1
kind: Deployment

metadata:
    name: receiver-microservice-deployment
    namespace: dev
    labels:
        app: receiver

spec:
    selector:
        matchLabels:
            app: receiver

    template:
        metadata:
            name: receiver-microservice
            labels:
                app: receiver
        spec:
            containers:
                - name: receiver-microservice
                  image: archismanmridha/rabbitmq-receiver-microservice:2.0.0
                  imagePullPolicy: IfNotPresent
                  resources:
                    limits:
                        cpu: 200m
                        memory: 256Mi
