apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: argo-events-resources
    namespace: argocd

spec:
    project: default

    source:
        repoURL: https://github.com/Archisman-Mridha/cloudnative-tools
        targetRevision: HEAD
        path: argo-ecosystem/kubernetes/argo/events
        directory:
            recurse: true

    destination:
        server: https://kubernetes.default.svc
        namespace: argo-events

    syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true