apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
    creationTimestamp: null
    name: secret
    namespace: default
spec:
    encryptedData:
        secret: AgB9t0FKEfMFs+icNv/Y4gSdYcvb59+EsdVWzN/+gFD5vjL/UvhfzT/Cgd+zkCnN3sPRVQ1ND29OSinTexXXHFjCu37RdGy+AKSw1W3CQsqzGH3bEHQfUZCO1DI6dJp1jNN4CRed4cVWArvSuAXQyT1hbsMSPYFxrjEGOje+DC9mj71bp3Efp2NY3QUwDEAKS/zTQUhgxksn7fPSe2Q2uuzG9tcvwtlAvIlF3xrvlT2cQM54wFqsmK6SRUd3RVp1OXdChc2vqABNTloldolIP9ureGsYgDjTxLcksjBMsBFNdsoWy5U5dYVOIr1oVi8lih+jA3vmHFGXSV8NLlr2YNE7J5wphbDJhUv6XC7Os0Labv1s/jnVR/YbBKNX/T91HDZcMkyjD42katQfOs2rMmF+DkG+EI/KkEIGuJ5MaIOYBrAzUmbES98az79V7zOz5ju/vRyjXoygvFHL/UOvLuY+HU3kq8559rXt3cc7+otQkuDiSKINMWPAeWtb2j90qZNX/L0JoqhOCqH59JBKklmr9HCKVU1NtGE0uVA8u80owTPoGASkIGK9YLxpgLjpr2NGr6gGj0totmtiYAhhZH1iucyZ6zpiahogSvo1H2W6wAu3M7GyihyflKDR/5OHySxSnjff1iO3ye31KAKl1Z2l8fbSV566k+Fsujl6jHNXpun5fVJqAcu2xUor73PSjsi+qVmZ
    template:
        metadata:
            creationTimestamp: null
            name: secret
            namespace: default
        type: Opaque
