apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: argo-workflows
    namespace: argocd

spec:
    project: default
    source:
        repoURL: https://github.com/Archisman-Mridha/cloudnative-tools.git
        targetRevision: HEAD
        path: argo/kubernetes/argo/workflows
    destination:
        server: https://kubernetes.default.svc
        namespace: default

    syncPolicy:
        automated:
            prune: true
            selfHeal: true