apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: kubernetes-gateway-api-crds
    namespace: argocd

spec:
    project: default

    source:
        repoURL: https://github.com/kubernetes-sigs/gateway-api
        targetRevision: release-0.4
        path: config/crd

    destination:
        server: https://kubernetes.default.svc
        namespace: default

    syncPolicy:
        automated:
            prune: true
            allowEmpty: true
            selfHeal: true